# Generated by Django 5.2.15 on 2026-07-07 06:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="título")),
                ("description", models.TextField(verbose_name="descripción")),
                ("date", models.DateTimeField(verbose_name="fecha y hora")),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Fácil"),
                            ("moderate", "Moderada"),
                            ("hard", "Difícil"),
                            ("very_hard", "Muy difícil"),
                        ],
                        max_length=20,
                        verbose_name="dificultad",
                    ),
                ),
                (
                    "location",
                    models.CharField(max_length=150, verbose_name="ubicación"),
                ),
                (
                    "meeting_point",
                    models.CharField(max_length=150, verbose_name="punto de encuentro"),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="número máximo de participantes",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organized_activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="organizador",
                    ),
                ),
            ],
            options={
                "verbose_name": "actividad",
                "verbose_name_plural": "actividades",
                "ordering": ["date"],
            },
        ),
    ]
