# Generated by Django 5.2.15 on 2026-07-07 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_registration"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="gpx_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="gpx/",
                validators=[django.core.validators.FileExtensionValidator(["gpx"])],
                verbose_name="archivo GPX",
            ),
        ),
    ]
