# Generated by Django 5.2.15 on 2026-07-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0003_activity_gpx_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="distance_km",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="distancia (km)",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="duration_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                verbose_name="duración estimada (horas)",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="elevation_gain_m",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="desnivel positivo (m)"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="equipment",
            field=models.TextField(
                blank=True,
                help_text="Material recomendado para la ruta: calzado, agua, crampones...",
                verbose_name="material necesario",
            ),
        ),
    ]
