# Generated by Django 5.2.15 on 2026-07-07 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0005_activitymessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="activity_photos/", verbose_name="imagen"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="pie de foto"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de subida"
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="activities.activity",
                        verbose_name="actividad",
                    ),
                ),
            ],
            options={
                "verbose_name": "foto de la actividad",
                "verbose_name_plural": "fotos de la actividad",
                "ordering": ["created_at"],
            },
        ),
    ]
