# Generated by Django 5.2.15 on 2026-07-08 17:04

import cordada.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0006_activityphoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="latitud"),
        ),
        migrations.AddField(
            model_name="activity",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="longitud"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="description",
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(5000)],
                verbose_name="descripción",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="equipment",
            field=models.TextField(
                blank=True,
                help_text="Material recomendado para la ruta: calzado, agua, crampones...",
                validators=[django.core.validators.MaxLengthValidator(2000)],
                verbose_name="material necesario",
            ),
        ),
        migrations.AlterField(
            model_name="activityphoto",
            name="image",
            field=models.ImageField(
                upload_to="activity_photos/",
                validators=[cordada.validators.validate_upload_size],
                verbose_name="imagen",
            ),
        ),
    ]
