# Generated by Django 5.2.15 on 2026-07-07 11:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="título")),
                ("description", models.TextField(verbose_name="descripción")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("footwear", "Calzado"),
                            ("clothing", "Ropa técnica"),
                            ("climbing", "Escalada"),
                            ("snow", "Esquí y snowboard"),
                            ("camping", "Acampada y vivac"),
                            ("backpacks", "Mochilas"),
                            ("electronics", "Electrónica y GPS"),
                            ("other", "Otros"),
                        ],
                        max_length=20,
                        verbose_name="categoría",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "Nuevo (sin estrenar)"),
                            ("like_new", "Como nuevo"),
                            ("good", "Buen estado"),
                            ("used", "Usado"),
                        ],
                        max_length=20,
                        verbose_name="estado del artículo",
                    ),
                ),
                (
                    "offer_type",
                    models.CharField(
                        choices=[
                            ("sale", "Venta"),
                            ("rent", "Alquiler (por día)"),
                            ("loan", "Préstamo gratuito"),
                        ],
                        default="sale",
                        max_length=10,
                        verbose_name="tipo de oferta",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="En alquileres, precio por día. En préstamos se deja vacío.",
                        max_digits=7,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="precio (€)",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="listings/",
                        verbose_name="fotografía",
                    ),
                ),
                (
                    "location",
                    models.CharField(max_length=100, verbose_name="localidad"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Disponible"),
                            ("reserved", "Reservado"),
                            ("closed", "Vendido / entregado"),
                        ],
                        default="available",
                        max_length=10,
                        verbose_name="estado del anuncio",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de publicación"
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="vendedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "anuncio",
                "verbose_name_plural": "anuncios",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_conversations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="interesado",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="market.listing",
                        verbose_name="anuncio",
                    ),
                ),
            ],
            options={
                "verbose_name": "conversación",
                "verbose_name_plural": "conversaciones",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MarketMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=1000, verbose_name="mensaje")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de envío"
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="market.conversation",
                        verbose_name="conversación",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="remitente",
                    ),
                ),
            ],
            options={
                "verbose_name": "mensaje del mercado",
                "verbose_name_plural": "mensajes del mercado",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                fields=("listing", "buyer"), name="unique_listing_buyer"
            ),
        ),
    ]
