# Generated by Django 5.2.15 on 2026-07-08 17:04

import cordada.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="description",
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(5000)],
                verbose_name="descripción",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="listings/",
                validators=[cordada.validators.validate_upload_size],
                verbose_name="fotografía",
            ),
        ),
    ]
