# Generated by Django 5.2.15 on 2026-07-09 06:53
# Editada a mano: crea ListingImage, copia la foto existente de cada
# anuncio al nuevo modelo y solo entonces elimina el campo antiguo.

import cordada.validators
import django.db.models.deletion
from django.db import migrations, models


def copy_listing_photos(apps, schema_editor):
    Listing = apps.get_model("market", "Listing")
    ListingImage = apps.get_model("market", "ListingImage")
    for listing in Listing.objects.exclude(photo="").exclude(photo__isnull=True):
        ListingImage.objects.create(listing=listing, image=listing.photo.name)


def delete_listing_images(apps, schema_editor):
    apps.get_model("market", "ListingImage").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_alter_listing_description_alter_listing_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="listings/",
                        validators=[cordada.validators.validate_upload_size],
                        verbose_name="imagen",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="market.listing",
                        verbose_name="anuncio",
                    ),
                ),
            ],
            options={
                "verbose_name": "imagen del anuncio",
                "verbose_name_plural": "imágenes del anuncio",
                "ordering": ["pk"],
            },
        ),
        migrations.RunPython(copy_listing_photos, delete_listing_images),
        migrations.RemoveField(
            model_name="listing",
            name="photo",
        ),
    ]
