# Generated by Django 5.2.15 on 2026-07-07 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sport",
                    models.CharField(
                        choices=[
                            ("hiking", "Senderismo"),
                            ("mountaineering", "Alpinismo"),
                            ("climbing", "Escalada"),
                            ("skiing", "Esquí"),
                            ("snowboarding", "Snowboard"),
                            ("trail_running", "Trail running"),
                            ("mtb", "Bici de montaña"),
                            ("canyoning", "Barranquismo"),
                        ],
                        max_length=20,
                        verbose_name="deporte",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Principiante"),
                            ("intermediate", "Intermedio"),
                            ("advanced", "Avanzado"),
                            ("expert", "Experto"),
                        ],
                        max_length=20,
                        verbose_name="nivel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "deporte del usuario",
                "verbose_name_plural": "deportes del usuario",
                "ordering": ["sport"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "sport"), name="unique_user_sport"
                    )
                ],
            },
        ),
    ]
