# Generated by Django 5.2.15 on 2026-07-08 17:04

import cordada.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_usersport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_photos/",
                validators=[cordada.validators.validate_upload_size],
                verbose_name="fotografía",
            ),
        ),
    ]
