# Generated by Django 5.2.15 on 2026-07-08 17:04

import cordada.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="posts/",
                validators=[cordada.validators.validate_upload_size],
                verbose_name="imagen",
            ),
        ),
    ]
