# Generated by Django 5.2.15 on 2026-07-09 06:53
# Editada a mano: crea PostImage, copia la imagen existente de cada
# publicación al nuevo modelo y solo entonces elimina el campo antiguo.

import cordada.validators
import django.db.models.deletion
from django.db import migrations, models


def copy_post_images(apps, schema_editor):
    Post = apps.get_model("feed", "Post")
    PostImage = apps.get_model("feed", "PostImage")
    for post in Post.objects.exclude(image="").exclude(image__isnull=True):
        PostImage.objects.create(post=post, image=post.image.name)


def delete_post_images(apps, schema_editor):
    apps.get_model("feed", "PostImage").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0002_alter_post_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="posts/",
                        validators=[cordada.validators.validate_upload_size],
                        verbose_name="imagen",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="feed.post",
                        verbose_name="publicación",
                    ),
                ),
            ],
            options={
                "verbose_name": "imagen de publicación",
                "verbose_name_plural": "imágenes de publicación",
                "ordering": ["pk"],
            },
        ),
        migrations.RunPython(copy_post_images, delete_post_images),
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
    ]
